### ISSUE TITLE
다국어 지원

### ISSUE THREAD

**Issue by SaidBySolo** [Saebasol/Hiyobot_deprecated#14]
https://docs.python.org/ko/3/library/gettext.html
http://babel.pocoo.org/en/latest/

**Comment by ghost** [comment]
다국어 지원을 이해할 수는 있는데, 이 봇이 번역이 필요할 정도로 해외 유저가 있을까요?

**Comment by SaidBySolo** [comment]
> 다국어 지원을 이해할 수는 있는데, 이 봇이 번역이 필요할 정도로 해외 유저가 있을까요?

기존 유저를 위한 지원이 아닙니다.
